AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  Gateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        FailOnWarnings: true
        DefaultAuthorizer: AWS_IAM

  Storage:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema: 
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  Backend:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: api
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Storage
      Environment:
        Variables:
          TABLE_NAME: !Ref Storage
      Events:
        RootHandler:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /{proxy+}
            Method: post

Outputs:
  Endpoint:
    Value: !Sub https://${Gateway}.execute-api.${AWS::Region}.amazonaws.com