// the proto buf version

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.2
// source: rpc/ledger/service.proto

// declare the package this file belongs to

package ledger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClaimDomainInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientRequestToken string `protobuf:"bytes,1,opt,name=ClientRequestToken,proto3" json:"ClientRequestToken,omitempty"` // we will use this to enforce idempotency - I'll explain this further in another post
	Subdomain          string `protobuf:"bytes,2,opt,name=Subdomain,proto3" json:"Subdomain,omitempty"`                   //
	Root               string `protobuf:"bytes,3,opt,name=Root,proto3" json:"Root,omitempty"`                             // We will assume we are claiming subdomains on a set of domains we happen to own
}

func (x *ClaimDomainInput) Reset() {
	*x = ClaimDomainInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_ledger_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimDomainInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimDomainInput) ProtoMessage() {}

func (x *ClaimDomainInput) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_ledger_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimDomainInput.ProtoReflect.Descriptor instead.
func (*ClaimDomainInput) Descriptor() ([]byte, []int) {
	return file_rpc_ledger_service_proto_rawDescGZIP(), []int{0}
}

func (x *ClaimDomainInput) GetClientRequestToken() string {
	if x != nil {
		return x.ClientRequestToken
	}
	return ""
}

func (x *ClaimDomainInput) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

func (x *ClaimDomainInput) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

type ClaimDomainOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain *Domain `protobuf:"bytes,1,opt,name=Domain,proto3" json:"Domain,omitempty"`
}

func (x *ClaimDomainOutput) Reset() {
	*x = ClaimDomainOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_ledger_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimDomainOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimDomainOutput) ProtoMessage() {}

func (x *ClaimDomainOutput) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_ledger_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimDomainOutput.ProtoReflect.Descriptor instead.
func (*ClaimDomainOutput) Descriptor() ([]byte, []int) {
	return file_rpc_ledger_service_proto_rawDescGZIP(), []int{1}
}

func (x *ClaimDomainOutput) GetDomain() *Domain {
	if x != nil {
		return x.Domain
	}
	return nil
}

type Domain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Root      string `protobuf:"bytes,2,opt,name=Root,proto3" json:"Root,omitempty"`
	Subdomain string `protobuf:"bytes,3,opt,name=Subdomain,proto3" json:"Subdomain,omitempty"`
}

func (x *Domain) Reset() {
	*x = Domain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_ledger_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain) ProtoMessage() {}

func (x *Domain) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_ledger_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain.ProtoReflect.Descriptor instead.
func (*Domain) Descriptor() ([]byte, []int) {
	return file_rpc_ledger_service_proto_rawDescGZIP(), []int{2}
}

func (x *Domain) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *Domain) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

var File_rpc_ledger_service_proto protoreflect.FileDescriptor

var file_rpc_ledger_service_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x70, 0x63, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x72, 0x22, 0x74, 0x0a, 0x10, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x44, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x2e, 0x0a, 0x12, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x12, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x75, 0x62, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x6f, 0x6f, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x52, 0x6f, 0x6f, 0x74, 0x22, 0x3b, 0x0a, 0x11, 0x43, 0x6c, 0x61, 0x69,
	0x6d, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x26, 0x0a,
	0x06, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x06, 0x44,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x3a, 0x0a, 0x06, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x52, 0x6f, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x52,
	0x6f, 0x6f, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x75, 0x62, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x32, 0x4c, 0x0a, 0x06, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x12, 0x42, 0x0a, 0x0b, 0x43,
	0x6c, 0x61, 0x69, 0x6d, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x18, 0x2e, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x72, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x1a, 0x19, 0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x43, 0x6c,
	0x61, 0x69, 0x6d, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x42,
	0x0c, 0x5a, 0x0a, 0x72, 0x70, 0x63, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_ledger_service_proto_rawDescOnce sync.Once
	file_rpc_ledger_service_proto_rawDescData = file_rpc_ledger_service_proto_rawDesc
)

func file_rpc_ledger_service_proto_rawDescGZIP() []byte {
	file_rpc_ledger_service_proto_rawDescOnce.Do(func() {
		file_rpc_ledger_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_ledger_service_proto_rawDescData)
	})
	return file_rpc_ledger_service_proto_rawDescData
}

var file_rpc_ledger_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpc_ledger_service_proto_goTypes = []interface{}{
	(*ClaimDomainInput)(nil),  // 0: ledger.ClaimDomainInput
	(*ClaimDomainOutput)(nil), // 1: ledger.ClaimDomainOutput
	(*Domain)(nil),            // 2: ledger.Domain
}
var file_rpc_ledger_service_proto_depIdxs = []int32{
	2, // 0: ledger.ClaimDomainOutput.Domain:type_name -> ledger.Domain
	0, // 1: ledger.Ledger.ClaimDomain:input_type -> ledger.ClaimDomainInput
	1, // 2: ledger.Ledger.ClaimDomain:output_type -> ledger.ClaimDomainOutput
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_ledger_service_proto_init() }
func file_rpc_ledger_service_proto_init() {
	if File_rpc_ledger_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_ledger_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimDomainInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_ledger_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimDomainOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_ledger_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Domain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_ledger_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_ledger_service_proto_goTypes,
		DependencyIndexes: file_rpc_ledger_service_proto_depIdxs,
		MessageInfos:      file_rpc_ledger_service_proto_msgTypes,
	}.Build()
	File_rpc_ledger_service_proto = out.File
	file_rpc_ledger_service_proto_rawDesc = nil
	file_rpc_ledger_service_proto_goTypes = nil
	file_rpc_ledger_service_proto_depIdxs = nil
}
